const namespace = 'user'

export const GET_USER_COORDINATES_REQUESTED = `${namespace}/GET_USER_COORDINATES_REQUESTED`
export const GET_USER_COORDINATES_SUCCEEDED = `${namespace}/GET_USER_COORDINATES_SUCCEEDED`
export const GET_USER_COORDINATES_FAILED = `${namespace}/GET_USER_COORDINATES_FAILED`
