import { FetchActionTypes } from "../../types"

const namespace = 'user'

export const GET_USER_COORDINATES_REQUESTED = `${namespace}/GET_USER_COORDINATES_REQUESTED`
export const GET_USER_COORDINATES_SUCCEEDED = `${namespace}/GET_USER_COORDINATES_SUCCEEDED`
export const GET_USER_COORDINATES_FAILED = `${namespace}/GET_USER_COORDINATES_FAILED`

export const READ_USER_COORDINATES: FetchActionTypes = [GET_USER_COORDINATES_REQUESTED, GET_USER_COORDINATES_SUCCEEDED, GET_USER_COORDINATES_FAILED]

export const GET_USER_ADDRESS_REQUESTED = `${namespace}/GET_USER_ADDRESS_REQUESTED`
export const GET_USER_ADDRESS_SUCCEEDED = `${namespace}/GET_USER_ADDRESS_SUCCEEDED`
export const GET_USER_ADDRESS_FAILED = `${namespace}/GET_USER_ADDRESS_FAILED`

export const READ_USER_ADDRESS: FetchActionTypes = [GET_USER_ADDRESS_REQUESTED, GET_USER_ADDRESS_SUCCEEDED, GET_USER_ADDRESS_FAILED]
