import { FetchActionTypes } from '../../types'

const namespace = 'locations'

export const READ_LOCATIONS_REQUESTED = `${namespace}/READ_LOCATIONS_REQUESTED`
export const READ_LOCATIONS_SUCCEEDED = `${namespace}/READ_LOCATIONS_SUCCEEDED`
export const READ_LOCATIONS_FAILED = `${namespace}/READ_LOCATIONS_FAILED`

export const READ: FetchActionTypes = [READ_LOCATIONS_REQUESTED, READ_LOCATIONS_SUCCEEDED, READ_LOCATIONS_FAILED]

export const LOAD_MORE_LOCATIONS_REQUESTED = `${namespace}/LOAD_MORE_LOCATIONS_REQUESTED`
export const LOAD_MORE_LOCATIONS_SUCCEEDED = `${namespace}/LOAD_MORE_LOCATIONS_SUCCEEDED`
export const LOAD_MORE_LOCATIONS_FAILED = `${namespace}/LOAD_MORE_LOCATIONS_FAILED`

export const LOAD_MORE: FetchActionTypes = [LOAD_MORE_LOCATIONS_REQUESTED, LOAD_MORE_LOCATIONS_SUCCEEDED, LOAD_MORE_LOCATIONS_FAILED]
